name: Playwright Tests

# 1. KAPAN pipeline ini dijalankan?
on:
  push:
    branches: [ main, master ] # Berjalan saat ada kode baru masuk ke branch main/master
  pull_request:
    branches: [ main, master ]

# 2. APA yang harus dilakukan oleh robot server?
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest # Menggunakan OS Linux Ubuntu virtual
    
    steps:
    - name: Mengambil kode dari repository
      uses: actions/checkout@v4
      
    - name: Menyiapkan NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20
        
    - name: Install Dependencies (Library)
      run: npm ci
      
    - name: Install Browser Playwright
      run: npx playwright install --with-deps
      
    - name: Menjalankan Test Playwright
      run: npx playwright test
      
    # 3. MENYIMPAN HASIL TEST (Report)
    - name: Menyimpan Laporan (Artifact)
      uses: actions/upload-artifact@v4
      if: always() # Report tetap disimpan walaupun test ada yang gagal (FAIL)
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 7